apiVersion: v1
kind: ConfigMap
metadata:
  name: channel-landing-page
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>Из цифры в пластик</title>
        <style>
          body { font-family: sans-serif; text-align: center; margin-top: 50px; background-color: #f4f4f9; }
          h1 { color: #333; }
          p { color: #666; font-size: 18px; }
        </style>
      </head>
      <body>
        <h1> Чётко! </h1>
        <p>Привет! Это тестовая страница, работающая внутри домашнего кластера K3s.</p>
        <p>Полет нормальный!</p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: channel-landing-page
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: my-web-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
